//! Generates one distinct stub function per Android symbol Roblox imports.
//!
//! The symbol list is `docs/analysis/undefined-symbols.tsv`, produced by the
//! bootstrap enumeration (see docs/framework-api-inventory.md §6). Each symbol
//! needs its *own* address so a stub hit identifies which symbol was called —
//! hence generated code rather than one shared stub.
//!
//! **This file is no longer what decides whether a symbol resolves.** It used
//! to be: `symtab::build` iterated exactly the array generated here, so a name
//! absent from the TSV was never classified, never registered, and the load
//! failed at `DT_NEEDED`. `hypotf` and then `getpwuid_r` each stopped the
//! client that way, and each was an ordinary C function the host had all
//! along. `symtab::build` now reads the engine's imports from the ELF and
//! resolves the union; what this generates is the stub set, and the individual
//! addresses that let a hit name its symbol. See
//! `docs/adr/ADR-034-symbol-resolution-asks-the-library.md`.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let tsv = root.join("docs/analysis/undefined-symbols.tsv");
    println!("cargo:rerun-if-changed={}", tsv.display());

    let text = std::fs::read_to_string(&tsv)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", tsv.display()));

    let mut symbols: BTreeSet<&str> = BTreeSet::new();
    for line in text.lines() {
        if let Some((_consumer, symbol)) = line.split_once('\t') {
            let s = symbol.trim();
            // libdl.so's symbols are provided by the linker itself.
            if !s.is_empty() && !matches!(s, "dlopen" | "dlsym" | "dlclose" | "dlerror"
                                             | "dladdr" | "dl_iterate_phdr" | "dlvsym") {
                symbols.insert(s);
            }
        }
    }

    let mut out = String::from(
        "// Generated by build.rs from docs/analysis/undefined-symbols.tsv. Do not edit.\n\n",
    );
    for (i, _) in symbols.iter().enumerate() {
        let _ = writeln!(
            out,
            "extern \"C\" fn stub_{i}() -> i64 {{ crate::stubs::hit({i}) }}"
        );
    }
    let _ = writeln!(out, "\npub const SYMBOLS: [(&str, extern \"C\" fn() -> i64); {}] = [", symbols.len());
    for (i, s) in symbols.iter().enumerate() {
        let _ = writeln!(out, "    ({s:?}, stub_{i}),");
    }
    let _ = writeln!(out, "];");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("generated_stubs.rs");
    std::fs::write(&dest, out).unwrap();

    println!("cargo:warning=generated {} stubs", symbols.len());
}
